# Generated by Django 5.1 on 2024-09-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("cat_id", models.AutoField(primary_key=True, serialize=False)),
                ("cat_name", models.CharField(max_length=100)),
            ],
        ),
    ]
