# Generated by Django 5.1 on 2024-09-20 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextr", "0003_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_no", models.IntegerField()),
                ("section_name", models.CharField(max_length=100)),
                (
                    "m_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("video", "Video")],
                        default="pdf",
                        max_length=5,
                    ),
                ),
                ("m_title", models.CharField(max_length=100)),
                ("file_loc", models.FileField(upload_to="")),
                ("duration", models.FloatField(blank=True, null=True)),
                ("slug", models.SlugField(default="", max_length=300)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codextr.course"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course_id", "section_no", "m_title"),
                        name="unique_course_material",
                    )
                ],
            },
        ),
    ]
