# Generated by Django 5.1 on 2024-09-20 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextr", "0004_coursematerial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "s_user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codextr.student",
                    ),
                ),
            ],
        ),
    ]
