# Generated by Django 5.1 on 2024-09-21 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextr", "0004_coursematerial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codextr.course"
                    ),
                ),
                (
                    "s_user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codextr.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Digital_Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(max_length=100)),
                ("card_no", models.IntegerField()),
                ("exp_date", models.DateField()),
                ("cvc", models.IntegerField()),
                ("c_balance", models.FloatField(default=0.0)),
                (
                    "s_user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codextr.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("t_id", models.AutoField(primary_key=True, serialize=False)),
                ("t_date", models.DateField(auto_now_add=True)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codextr.course"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codextr.cart"
                    ),
                ),
                (
                    "s_user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codextr.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating_no", models.IntegerField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codextr.course"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codextr.cart"
                    ),
                ),
                (
                    "s_user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codextr.student",
                    ),
                ),
                (
                    "t_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codextr.transaction",
                    ),
                ),
            ],
        ),
    ]
