# Generated by Django 5.1 on 2024-09-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextr", "0005_cart_digital_wallet_transaction_enroll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="bank_account",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="routing_no",
            field=models.IntegerField(default=0),
        ),
    ]
