# Generated by Django 5.1 on 2024-09-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codextr", "0008_enroll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enroll",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="enroll",
            name="rating_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
